### PR TITLE
BS4 => Pure CSS Navigation Bar.

### LINKED ISSUE #580: Removal of Bootstrap 4 in Nav-bar. 🎨
**Is your feature request related to a problem? Please describe.**
Remove `Bootstrap 4` classes used in `navigation-bar` with `custom css`, one way is to copy properties associated with BS4 classes and add those properties to your `custom classes`, or design `navigation-bar` from scratch using your own css.

**Describe the solution you'd like**
Remove `navigation-bar` BS4 => Pure css.

**Describe alternatives you've considered**
Issue can be considered part of #403 

**Additional context**
Let me know if issue is not clear. ⚡️

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #580 

Summary of the changes:
- Removed dependency of BS4
- Added custom styles on the navbar

Here's the working example:
The video might lag a little

Ignitus

### CODE REVIEW

**Comment by abhu-A-J** [comment]
@divyanshu-rawat Does this look okay. The only thing I couldn't replicate was the transition on the burger where it transforms from 3 lines to an arrow to cross. I skipped the middle part.

**Comment by divyanshu-rawat** [comment]
@abhu-A-J It looks good to me, the only thing that I believe can be improved is `handleSmallerScreen()` that makes use of `querySelector` & `classList` methods that belong to native vanilla JS that I believe can be done in a react-way by declaring a state in Navigation Component. Problems with style & classes can be easily solvable if you reply on` css-in-js`,  that's why we use emotion, for example just see how I manipulate css using react states here. using [emotion](https://emotion.sh/docs/styled),  https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-UserInterfaceKit/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx.


Nevertheless I will take care of improving it and removing dependency on `querySelectors` & `classList` in the future , I must say great work ⚡️.

**Comment by abhu-A-J** [comment]
> @abhu-A-J It looks good to me, the only thing that I believe can be improved is `handleSmallerScreen()` that makes use of `querySelector` & `classList` methods that belong to native vanilla JS that I believe can be done in a react-way by declaring a state in Navigation Component. Problems with style & classes can be easily solvable if you reply on` css-in-js`, that's why we use emotion, for example just see how I manipulate css using react states here. using [emotion](https://emotion.sh/docs/styled), https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-UserInterfaceKit/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx.
> 
> Nevertheless I will take care of improving it and removing dependency on `querySelectors` & `classList` in the future , I must say great work ⚡️.

Thanks!👍 😄  
Yes I'm getting around to learning that part now since most of the styles are migrated to that form, hopefully I'll do that from near future (when I get the total hang of it)

**Comment by divyanshu-rawat** [comment]
> > @abhu-A-J It looks good to me, the only thing that I believe can be improved is `handleSmallerScreen()` that makes use of `querySelector` & `classList` methods that belong to native vanilla JS that I believe can be done in a react-way by declaring a state in Navigation Component. Problems with style & classes can be easily solvable if you reply on` css-in-js`, that's why we use emotion, for example just see how I manipulate css using react states here. using [emotion](https://emotion.sh/docs/styled), https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-UserInterfaceKit/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx.
> > Nevertheless I will take care of improving it and removing dependency on `querySelectors` & `classList` in the future , I must say great work ⚡️.
> 
> Thanks!👍 😄
> Yes I'm getting around to learning that part now since most of the styles are migrated to that form, hopefully I'll do that from near future (when I get the total hang of it)

Thanks a lot I also think so :)

**Pull request merged**
