### PR TITLE
:bug: link to complete div instead of just image

### LINKED ISSUE #758: CSS minor issue in login/signup screen
**Login/SignUp as Student/Professor Card**
When a user hover on the card the scale transition occur on the card but link to the next page only available on the image , even though the cursor is pointer.

**To Reproduce**
1. Go to 'Signup/login'
2. Hover on professor/student card
3. Try to click outside image

**Expected behaviour**
Either card should not have cursor as pointer or whole card should be provided with link to next page.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ashishnagpal2498**
fixes #758 
Changed div to complete Link tag so that where ever the user clicks it should go to next page.

### CODE REVIEW

**Comment by Marvin9** [comment]
Working as expected 👍

**Comment by ashishnagpal2498** [comment]
Hi @divyanshu-rawat , I just , the UI works perfectly fine. Margin was added before only at smaller pixels.
Original UI
image

**Comment by divyanshu-rawat** [comment]
> Hi @divyanshu-rawat , I just checked, the UI works perfectly fine. Margin was added before only at smaller pixels.
> Original UI
> image

@Marvin9 can you validate this?

**Comment by divyanshu-rawat** [comment]
bot test this

**Comment by Marvin9** [comment]
@divyanshu-rawat Couldn't get what is the issue 😥

**Comment by ashishnagpal2498** [comment]
@divyanshu-rawat @Marvin9 @Paarmita  Kindly add difficulty level of PR.

**Pull request merged**
