### PR TITLE
Added unit tests for ignitus-SideNavigation

### PR DESCRIPTION
**Pull request by Dishebh**
For issue: #519

### CODE REVIEW

**Comment by Marvin9** [comment]
Thanks. I noticed ```Layers``` is repeating, So I will generalize it. 

For now, convert this PR to draft.

**Comment by Marvin9** [comment]
Now you can update tests.

**Comment by Dishebh** [comment]
Making another PR for it.

**Comment by Dishebh** [comment]
@Marvin9 I wrote the tests, and they seem fine to me. But after the refactoring of the `ignitus-SideNavigation` to create a `CommonLayer`, there is this error thrown when I run my tests: 

```node.js
You are trying to create a styled element with an undefined component.
    You may have forgotten to import it.

      17 | `;
      18 | 
    > 19 | export const Layer = styled(CommonLayer)`
         |                      ^
      20 |   display: flex;
      21 |   align-items: center;
      22 |   justify-content: flex-start;
```

Despite what the error says, the `CommonLayer` is getting imported:

```node.js
import { CommonLayer } from '../Common/Layer';
```

Please let me know if you know something about it.

**Comment by Marvin9** [comment]
It seems weird. 
I tested and cannot found why this happens. [Here](https://github.com/styled-components/styled-components/issues/1449) is related issue but for ```styled-components```. 

I will notify you if I am able to find solution. Till then you can try yourself or leave it as it is.

**Comment by Dishebh** [comment]
> It seems weird.
> I tested and cannot found why this happens. [Here](https://github.com/styled-components/styled-components/issues/1449) is related issue but for `styled-components`.
> 
> I will notify you if I am able to find solution. Till then you can try yourself or leave it as it is.

Guess I'll leave it as it is for now, and come back sometimes later

**Comment by Marvin9** [comment]
@divyanshu-rawat Can you please reproduce it and debug? There is something related to emotion. Check if you can figure this strange issue.

**Comment by divyanshu-rawat** [comment]
@Marvin9 I will have a look soon ;)

**Comment by divyanshu-rawat** [comment]
@Dishebh should we close this now?

**Comment by Dishebh** [comment]
Yeah, will close it for now.

**Pull request closed without merging**
