### PR TITLE
Added lazy loading of images for both TS and JS supported components

### LINKED ISSUE #583: Improve page insights.
Please find attached google page insights repot for `http://www.ignitus.org/`.
It looks good, but still we have some problem with rendering of images.
It would be great if someone can find a way to optimise it.

screencapture-developers-google-speed-pagespeed-insights-2020-03-05-16_52_32

@Paarmita do you have idea about the same!.

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #583 
Implemented the lazy loading of images concept for both components written in JS and TS. 
Breaking Changes: Addition of 2 new npm packages to achieve the same tasks mentioned above.

### CODE REVIEW

**Comment by gittysachin** [comment]
Great job @abhu-A-J. But the time of first-input-delay has increased, not every time but sometimes when the browser will deal heavy loads then it will affect the response to any clicked link or button pressed. @divyanshu-rawat it's because of the `react-lazy-load-image-component` package. And this npm package is the reason for slightly increased load time as well.

**Comment by divyanshu-rawat** [comment]
@gittysachin there is improvement in `Max Potential First Input Delay`, `Time to Interactive`.

**Comment by abhu-A-J** [comment]
@divyanshu-rawat @gittysachin my two cents on this matter. 

-  I can see font awesome icons are used very less around 9 of them on about us page and footer), but we'rehaving an npm package for the entire thing. We can easily replace with SVG's and it will reduce bundle size as well.

- In the background the image when compressed  could save about 64%. 

Screenshot (34)

- The resume.svg although not that much still 28.2% save is there. Here a picture: 

Screenshot (33)

**Comment by gittysachin** [comment]
> @gittysachin there is improvement in `Max Potential First Input Delay`, `Time to Interactive`.

@divyanshu-rawat It's showing completely different result now. Last time when I checked, it was showing results as I previously described.

**Comment by divyanshu-rawat** [comment]
> @divyanshu-rawat @gittysachin my two cents on this matter.
> 
> * I can see font awesome icons are used very less around 9 of them on about us page and footer), but we'rehaving an npm package for the entire thing. We can easily replace with SVG's and it will reduce bundle size as well.
> 
> The images used all all format aren't really compressed that well, a lot of improvements can be done. Here's what I achieved on manual compression.
> 
> * In the background the image when compressed  could save about 64%.
> 
> Screenshot (34)
> 
> * The resume.svg although not that much still 28.2% save is there. Here a picture:
> 
> Screenshot (33)

@abhu-A-J thanks a lot sound good, but now question arises how should we compress the used images? I think the current format is png. I know one to compress `svg` images, https://jakearchibald.github.io/svgomg/ but unfortunately we are serving `png`.

One solution is to have an component to render `svg` images, something like, 
```
type Props = HTMLAttributes<SVGElement>;

const Icon = (props : Props) => {
	return (
		<svg aria-label={title} role="img" viewBox="0 0 100 100" 
                   xmlns="http://www.w3.org/2000/svg" {...rest}>
		</svg>
	);
};
```

export default Icon;


What do you think what should be the approach according to you? cc @gittysachin

**Comment by divyanshu-rawat** [comment]
> > @gittysachin there is improvement in `Max Potential First Input Delay`, `Time to Interactive`.
> 
> @divyanshu-rawat It's showing completely different result now. Last time when I checked, it was showing results as I previously described. It's continuously changing for me as I refresh the results.

I also tried it, results seems to be different one opening it again.

**Comment by divyanshu-rawat** [comment]
@abhu-A-J sorry to say, Here I think cost of module is more in comparison to that of value, we are closing it for now keeping in mind the merge conflicts as well. :) thanks for your efforts we really appreciate it, Hope you might have learned some stuff while working in THIS PR 👍 


We are removing dependency on font-awesome like this way. https://github.com/Ignitus/Ignitus-client/tree/develop/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons

Feel free to let us know your views on the same.

**Comment by abhu-A-J** [comment]
> @abhu-A-J sorry to say, Here I think cost of module is more in comparison to that of value, we are closing it for now keeping in mind the merge conflicts as well. :) thanks for your efforts we really appreciate it, Hope you might have learned some stuff while working in THIS PR 👍
> 
> We are removing dependency on font-awesome like this way. https://github.com/Ignitus/Ignitus-client/tree/develop/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets/ignitus-Icons
> 
> Feel free to let us know your views on the same.

@divyanshu-rawat Ah! Feels bad that this couldn't make a difference to the repo, but no issues I understand your point. I'll look towards other issues and hopefully try to contribute in a better way. Loving the experience btw!!

**Pull request closed without merging**
