### PR TITLE
Added General Settings UI

### LINKED ISSUE #883: General settings UI 🎨
**Is your feature request related to a problem? Please describe.**

**Minimum Requirement:**
Create a new route `/settings` &  implement general user settings UI, you have to implement the part outlined in a black border.
Add route as `private route `so that it can't be accessed without authentication, private routes are listed here https://github.com/Ignitus/Ignitus-client/blob/master/src/ignitus-Routes/ignitus-DashboardRoutes/index.tsx
Create a  new directory `ignitus-DashboardSettings/generalSettings` in `src/ignitus-Dashboard`.
Inside `generalSettings` follow this structure.

Screenshot 2020-06-27 at 12 40 37

**Great to have:**
Along with the UI also add the side navigation so that page is complete.
Side navigation component can be found here http://www.ignitus.org/interface/sideNavigation

**Describe the solution you'd like**

Settings General

**Describe alternatives you've considered**
N.A

**Additional context**

Please pick Input component from here http://www.ignitus.org/interface/primaryInput
Please pick button component from buttons in design kit http://www.ignitus.org/interface/buttons
Let me know if you have any Questions 🎯

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #883

### CODE REVIEW

**Comment by Dishebh** [comment]
Added `/dashboard/settings` as a public route for now. If the UI changes seem fine, will add it as a `PrivateRoute` then :)

**Comment by Dishebh** [comment]
Preview URL: https://deploy-preview-891--peaceful-nightingale-55a1b7.netlify.app/dashboard/settings

**Comment by Dishebh** [comment]
Preview link: https://deploy-preview-891--peaceful-nightingale-55a1b7.netlify.app/dashboard/settings

**Comment by Dishebh** [comment]
I tried manipulating the input size, but that is just hard-coded in the component. So, to change it, I would have to make changes to the component itself; and that will cause a change in the places where the component is currently is use.

**Comment by Paarmita** [comment]
@Dishebh No issues, you can change the input component as we need to reduce the size eventually.

**Comment by Paarmita** [comment]
> @Dishebh Can you please align the margin and padding on the whole page with the design.
> Also, if possible reduce the input sizes as shown in the design to align better, use buttons that align with the text, etc.

@Dishebh I checked the recently deployed link, and the Ui is still not aligned. Can you please look into it.

**Comment by Dishebh** [comment]
@Paarmita can you please share the Figma design for this? I'm not sure where exactly I have to work on in the UI.

**Comment by divyanshu-rawat** [comment]
here we go @Dishebh https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=344%3A82

**Comment by Dishebh** [comment]
@Paarmita I tried reducing the width of the `main container` and increase the left margin. Please let me know if this was not what you were looking for? Thanks!

Screenshot from 2020-07-12 01-02-38

**Comment by divyanshu-rawat** [comment]
@Dishebh LGTM! but if you look at `Forgot your password? ` on a bigger screen, this is how it looks, it is somehow moved from its position.

Screenshot 2020-07-19 at 18 27 09

**Pull request merged**
