### PR TITLE
Added basicProfileDetails page and upload icon

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes part of issue #877 

Preview Link: https://deploy-preview-888--peaceful-nightingale-55a1b7.netlify.app/flow/basicProfileFlow

### CODE REVIEW

**Comment by Dishebh** [comment]
@Paarmita same here :)

**Comment by Dishebh** [comment]
PR #899 fixes the input size issue as well, now.

**Comment by divyanshu-rawat** [comment]
please compare with original UI, here is the link to the frame https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=3273%3A15

**Comment by Dishebh** [comment]
@divyanshu-rawat I'll update the UI of this after the PR #899 gets merged, as the I have changed the `Input` component there.

**Comment by divyanshu-rawat** [comment]
#899 is already merged! :)

**Review by divyanshu-rawat — APPROVED** [review]
LGTM!

**Pull request merged**
