### PR TITLE
unit test for component loader

### PR DESCRIPTION
**Pull request by upieez**
added snapshot for loader component. unable to think of edge cases. lmk if you need more tests

### CODE REVIEW

**Comment by upieez** [comment]
related to [https://github.com/Ignitus/Ignitus-client/issues/932](https://github.com/Ignitus/Ignitus-client/issues/932)

**Comment by Dishebh** [comment]
@upieez, write tests for asserting the number of `Spinner` and `Logo` components that are being rendered.

**Comment by upieez** [comment]
> @upieez, write tests for asserting the number of `Spinner` and `Logo` components that are being rendered.

awesome ok thank you! will do :)

**Comment by upieez** [comment]
Hey @Dishebh, any more tests I need to add? Are the tests cases I wrote ok?

**Review by Dishebh — APPROVED** [review]
The tests seem great!

**Comment by Dishebh** [comment]
@Marvin9, pls have a look at this as well

**Pull request merged**
