### PR TITLE
Master > Develop

### PR DESCRIPTION
**Pull request by divyanshu-rawat**
1. Job to automatic generate preview of pull request 🤖. #755 
2. Refactoring #761 
3. Migration #477 
4. Migration #476 
5. Flaky behaviour of Student signup & login. #765
6. [UIKit]: Expansion of text area inside Multimedia Input UI
7. Profile Card UI ☘️ #769
8. Progress - Migration to export const #770 
9. fix: removed console warnings #772 
10. Keep white background on navbar constant in Home and About page #764

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@Marvin9 can you try your bot here now? :)

**Comment by divyanshu-rawat** [comment]
bot test this

**Comment by Marvin9** [comment]
Unfortunately we cannot test anywhere unless it is not merged  on master branch. 🙁

**Comment by Marvin9** [comment]
@divyanshu-rawat Why you always merge in develop first? Why not master branch directly?

**Comment by divyanshu-rawat** [comment]
@Marvin9 this is how release process usually is and is also helpful to find bugs, s everyone is working on develop so if anyone encounters any bug then we won't be merging our changes to master, apart from that It is also helpful to write release notes https://github.com/Ignitus/Ignitus-client/releases , if you merge every PR to master then how you will make a release? you can't release for every single PR, each Master > Develop indicates all the features and corresponding release notes.

**Pull request merged**
