### PR TITLE
[ignitus-UIBook]: Added Signup progress component.

### LINKED ISSUE #668: Signup flow Progress Bar UI
**Describe the solution you'd like**
Implementation of the attached Progress bar based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Molecules](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Molecules) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

Capture

Put the animations for going from one step to other. Taking reference of UI
 
loan-application-ui

### PR DESCRIPTION
**Pull request by Marvin9**
Fix #668 

- Container of component can be modified with ```@emotion/styled```. 
- It accepts ```steps``` & ```current``` as props and render accordingly.

See ```/interface/progress``` of this PR.

### CODE REVIEW

**Comment by Paarmita** [comment]
Behavior and UI look good to me. Can you please add this component under `Templates`

**Comment by Marvin9** [comment]
@Paarmita 
Do I need to move folder to ```Templates``` as well?

**Comment by Paarmita** [comment]
@Marvin9 Can you please increase the width of the lines and accordingly change the transition time delay. As we will be using this in the whole screen size

**Comment by Marvin9** [comment]
These thing can be modified through props.

- Line's ```width, height, transition duration```
- Circle's ```size, delay duration```

@Paarmita Can you please check it.

**Pull request merged**
