### PR TITLE
Clean SharedAuth component

### PR DESCRIPTION
**Pull request by Marvin9**
Is it good? Or should I further partition forms' component.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
Please resolve the merge conflicts then i think we are good to merge this to `develop`.

**Comment by Marvin9** [comment]
@divyanshu-rawat I will divide it further soon. Can I help anything related to typescript migration? Few components are still jsx.

**Comment by divyanshu-rawat** [comment]
> @divyanshu-rawat I will divide it further soon. Can I help anything related to typescript migration? Few components are still jsx.

Yup If you want to learn something new why don't you give Emotion a try along with TS.
These day react + emotion + TS are trending a lot ;)

**Comment by Marvin9** [comment]
@divyanshu-rawat Are you planning to completely pull out bootstrap?

**Comment by divyanshu-rawat** [comment]
> @divyanshu-rawat Are you planning to completely pull out bootstrap?

Its already pulled out , now we have to get rid of remaining stuff ;)

**Pull request merged**
