### PR TITLE
Fixed signup page styling for mobile devices.

### PR DESCRIPTION
**Pull request by abhishekjain35**
## Description
I have fixed styling of signup page. Previously cards were not aligned properly on smaller devices. I have fixed this issue in this PR.

## Motivation and Context
I found this project under GirlScript summer of code.
This PR refers to #541 issue.

## How Has This Been Tested?
I have tested these changes in devices with different **view width**. Styling seems to work fine after these changes.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@abhishekjain35 looks good to me, can you please do the same for login page as well :).

**Comment by divyanshu-rawat** [comment]
> @abhishekjain35 looks good to me, can you please do the same for login page as well :).

Let me know if you can replicate the same for login page as well :) , then I think we are good to merge 🚀 .

**Comment by abhishekjain35** [comment]
@divyanshu-rawat I can surely do it sir but this particular issue is for signup page. Please create a new issue for login page and assign it to me. so that I can start working on it. If you still think I should work on the sign-in page in this PR only then it's fine I can do it. But creating a new issue would be a better option, sir.

**Comment by abhishekjain35** [comment]
I've fixed sign in page too, please review it.

**Comment by divyanshu-rawat** [comment]
@abhishekjain35 I have assigned the issue to be of type medium so that you can get more points, now if possible can you also resolve suggestions by `hound`? for instance this https://github.com/Ignitus/Ignitus-client/pull/555#discussion_r386321857 and others as well 👍

**Comment by abhishekjain35** [comment]
Sir, I have fixed all the suggestions of hound bot. Please review the PR.

**Comment by vaishnavi-janardhan** [comment]
@divyanshu-rawat Please change the label `GSSOC'20` to `gssoc20`

**Pull request merged**
