### PR TITLE
Added tests for ignitus-ToggleButtons

### PR DESCRIPTION
**Pull request by Dishebh**
For issue: #519

### CODE REVIEW

**Comment by Dishebh** [comment]
> Add `handleClick` prop in `ToggleButtonInterface`. simulate both side click & `expect(mock_function).toHaveBeenCalledWith(bar);`

Added `handleClick` prop in `toggleButtoninterface.test.tsx`

**Comment by Dishebh** [comment]
@Marvin9 Are the changes fine now?

**Comment by Dishebh** [comment]
@Marvin9 Added test for categories toggle on click.

**Comment by Dishebh** [comment]
And here too (labels), thanks!

**Comment by divyanshu-rawat** [comment]
cool :)

**Pull request merged**
