### PR TITLE
issue #616 improvements in CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by kamal-kaur04**

### CODE REVIEW

**Comment by kamal-kaur04** [comment]
@Paarmita  Why is it failing? Any idea.

**Comment by divyanshu-rawat** [comment]
@kamal-kaur04 I will fix it now, but next time please keep on your branch up to date. :)

**Comment by kamal-kaur04** [comment]
> @kamal-kaur04 I will fix it now, but next time please keep on your branch up to date. :)

I apologize for the issue. Will keep it in mind next time :)
How will it be merged? Do I have to make some changes?

**Comment by divyanshu-rawat** [comment]
@kamal-kaur04 I will tc of it thanks :)

**Comment by kamal-kaur04** [comment]
Hello, @divyanshu-rawat, Will I be getting any points for this issue as it was raised by me?

**Pull request merged**
