### PR TITLE
fix: Bug in nav bar

### LINKED ISSUE #316: UI of navigation bar in Sign in / Sign up page
**Describe the bug**
The background of navigation bar of login/signup page at certain width(for me between 1000-1100px) is white including the links.

**To Reproduce**
1. Go to http://www.ignitus.org/Login 
2. Open dev tools(Ctrl + Shift + i)
3. Resize width
4. Bug will be seen somewhere between 1000 to 1200 px width 

**Expected behavior**
Navigation bar either show hamburger icon without links (or) show the links in blue background.

**Screenshots**
Screenshot from 2019-05-11 21-39-01

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Brave
 - Version: Chromium 72

### PR DESCRIPTION
**Pull request by CDharmateja**
## Description
Fixes the but in the nav bar

## Motivation and Context

fixes #316 

## How Has This Been Tested?

Bug no longer appears by resizing from dev tools

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Paarmita** [comment]
Hey @CDharmateja, Thanks for the PR, but the expected UI on the home of the navbar is this
Screenshot 2019-05-13 at 2 44 11 PM
And for the issue that you mentioned only happens in Ubuntu OS so you need to correct based on that.

**Comment by CDharmateja** [comment]
@Paarmita I have made the changes. I have mean't I am using Ubuntu but this issue can be seen in other OS too in window size between 992 to 1200px.

**Comment by CDharmateja** [comment]
@Paarmita I have made changes. I have mean't I am using ubuntu but this issue can be seen any OS and browser with screen size between 992px and 1200 px.

**Comment by divyanshu-rawat** [comment]
@CDharmateja Hope you are doing well, is this PR good for merge, kindly let me know 😄

**Comment by CDharmateja** [comment]
@divyanshu-rawat I think its good to merge now.

**Pull request merged**
