### PR TITLE
Added Scroll Bar component

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes issue: #671 

Added `ignitus-ScrollBar` component under `Molecules` at `/interface/scrollBar` route.

### CODE REVIEW

**Comment by Dishebh** [comment]
@divyanshu-rawat pls review

**Comment by divyanshu-rawat** [comment]
@Paarmita can you please review the UI/UX? :)

**Comment by Paarmita** [comment]
Reference scrollbar UI
Screenshot 2020-05-19 at 9 32 57 AM

@Dishebh , PR scrollbar UI doesn't look similar to what I suggested. Can you please look for some examples in codepen and make it look similar to the reference one. I guess you did like style 9 in here https://codepen.io/devstreak/pen/dMYgeO, but we can pick style 1 as it has rounded borders. 

Screenshot 2020-05-19 at 9 33 04 AM

**Comment by Dishebh** [comment]
> Reference scrollbar UI
> Screenshot 2020-05-19 at 9 32 57 AM
> 
> @Dishebh , PR scrollbar UI doesn't look similar to what I suggested. Can you please look for some examples in codepen and make it look similar to the reference one. I guess you did like style 9 in here https://codepen.io/devstreak/pen/dMYgeO, but we can pick style 1 as it has rounded borders.
> 
> Screenshot 2020-05-19 at 9 33 04 AM

Added round borders @Paarmita

**Pull request merged**
