### PR TITLE
fixed PasswordInput margin

### PR DESCRIPTION
**Pull request by Dishebh**
Fixed the UI of PasswordInput

#### Before Changes:
Screenshot from 2020-07-21 12-16-53

#### After changes:
Screenshot from 2020-07-21 12-15-21

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
Screenshot 2020-07-21 at 12 04 48

Doesn’t seem to fix.

**Comment by Dishebh** [comment]
@divyanshu-rawat I guess this fixes it

**Comment by divyanshu-rawat** [comment]
No :) 
Screenshot 2020-08-02 at 17 18 16

**Comment by Dishebh** [comment]
@divyanshu-rawat can you pls share the resolution of the screen which produces the issue :sweat_smile:, I am (somehow) not able to reproduce it.

**Review by Marvin9 — COMMENTED** [review]
Screenshot from 2020-09-04 10-31-35

Are you trying to make it same size?

**Comment by Dishebh** [comment]
> Screenshot from 2020-09-04 10-31-35
> 
> Are you trying to make it same size?

Nope, on

> Screenshot from 2020-09-04 10-31-35
> 
> Are you trying to make it same size?

Nope, only to stack them properly (like the one given in after changes in PR description). Basically, to revert them to their original layout.

**Comment by Marvin9** [comment]
Let's wait what @divyanshu-rawat got to say about it.

**Review by divyanshu-rawat — APPROVED** [review]
LGTM!

**Pull request merged**
