### PR TITLE
Altered Testimonial-carousel/UI 🎨

### PR DESCRIPTION
**Pull request by aysp-99**
Resolves- Issue #526 

**Changed the UI of Testimonial Component -**

- Achieved the representation of snippets of testimonials with quotation marks.
- Added user images(avatar).
- Removed the chevron icons.
- Added nav-slider for navigating through the snippets.

s6KoczSuDT

### CODE REVIEW

**Comment by aysp-99** [comment]
- There are some issues with the UI.
When the webpage is resized, the quotation icons doesn't stay aligned with the text. 
1JQwx3QEvO
 I tried implementing it with transform and display properties, but still it was not a functional solution. 
- The avatar(user) image is static for all the snippets. It can be implemented by `flexbox` property, though it can get complicated with all the code. 
- I tried implementing the logic for the navigation part, but couldn't implement it properly. So, I added the `onClick` event to the first and the last image(icon) temporarily.

**Comment by divyanshu-rawat** [comment]
Secondly, clicking on the avatars are not working properly, like the testimonials are not changing. 

Screen Recording 2020-03-29 at 22 32 54

**Comment by aysp-99** [comment]
@divyanshu-rawat I fixed the UI issues including the quotation marks issue, which now works and added functionality of navigating through testimonials to nav-avatar.

**Comment by aysp-99** [comment]
Please let me know if I need to correct any mistakes or if I missed something.

**Comment by divyanshu-rawat** [comment]
@aysp-99 sure I will review your pr soon, thanks a lot :)

**Pull request merged**
