### PR TITLE
[ User Interface ]: n-level nesting in sidebar with indentation

### PR DESCRIPTION
**Pull request by Marvin9**
n_level

### CODE REVIEW

**Comment by Marvin9** [comment]
@divyanshu-rawat #733 is good approach. Code is clean and readable too.

Complexity remains same because eventually Extension's Navigation is loop itself. Complexity should not be concern I think 🤔

**Comment by Marvin9** [comment]
Let's go with #733 as it is more readable.

**Comment by divyanshu-rawat** [comment]
@Marvin9 nope I believe you wrong in this context, complexity will be affected for sure, as you are running nested loops. Imagine a huge dataset, then you are iterating over I like this.

https://github.com/Ignitus/Ignitus-client/blob/9ba03d1b66714799c6a52415bd424dff84ff4729/src/ignitus-UserInterfaceBook/InterfaceSideNavigation/Components/interfaceSideNavigation.tsx#L15

```
    {edges.map(edge => (
      <NavigationLayers edge={edge} key={edge.title} level={0} />
    ))}
```

And then inside the NavigationLayers like this.

**Comment by Marvin9** [comment]
Ook. Let's imagine we have 1000 edges, each edge has 10 children.

## In my approach

```javascript
edges.map
```
will iterate 1000 times.

Where in each iteration

```javascript
edge.children.map
```
will iterate 10 times.

***Total iteration:*** 10000

## In your approach

Inside ```NavigationLayers```

```javascript
edges.map
```
will iterate 1000 times.

In each iteration.
```Layers``` will be called.
```Extension``` will be called.
as we know each edge has 10 children, ```NavigationLayers``` will be called inside ```Extension```.

now, Again 10 iteration will happen inside ```NavigationLayers``` 
```javascript
edges.map
```

***Total Iteration:*** 10000

Got my point?

**Comment by divyanshu-rawat** [comment]
> Ook. Let's imagine we have 1000 edges, each edge has 10 children.
> 
> ## In my approach
> ```js
> edges.map
> ```
> 
> will iterate 1000 times.
> 
> Where in each iteration
> 
> ```js
> edge.children.map
> ```
> 
> will iterate 10 times.
> 
> _**Total iteration:**_ 10000
> 
> ## In your approach
> Inside `NavigationLayers`
> 
> ```js
> edges.map
> ```
> 
> will iterate 1000 times.
> 
> In each iteration.
> `Layers` will be called.
> `Extension` will be called.
> as we know each edge has 10 children, `NavigationLayers` will be called inside `Extension`.
> 
> now, Again 10 iteration will happen inside `NavigationLayers`
> 
> ```js
> edges.map
> ```
> 
> _**Total Iteration:**_ 10000
> 
> Got my point?

Cool, Got it, now Imagine the every first child has children then in your approach in 1st iteration. number of loops that will 1st time will be 3, but in my one its 2.

export const edges: Edges[] = [
  {
    title: 'Atoms',
    children: [
      {
        title: 'Color Palette',
        children: [],
      }]
}];


An average map takes : ~469 microseconds.
https://hackernoon.com/3-javascript-performance-mistakes-you-should-stop-doing-ebf84b9de951

so running a single map with `10k iterations & 2 maps` that will be equivalent to 10k iterations I believe still running single map will be more performant.

**Comment by Marvin9** [comment]
Interesting, 

Lets now assume 1 edge having 10 children each children has 10 children.

## My approach

```javascript
edges.map
```
1 iteration.

```javascript
edges.children.map
```
10 iterations.

in each iteration ```NavigationLayers``` is called.

```javascript
edges.children.map
```
10 iterations.

***Total iterations*** : 100


##  Your approach

```
edge.map
```
1 iteration

```Layers``` will be called.
```Extension``` will be called.
Edge has 10 children, again ```NavigationLayers``` will be called.

```javascript
edges.map
```
10 Iterations.

In each iteration ```Layers``` will be called.
```Extension``` will be called.
Each edge has 10 children, again ```NavigationLayers``` will be called.

```javascript
edges.map
```
10 Iterations.

As no edge has children, no further ```NavigationLayers``` call.

***Total Iterations:*** 100

#### We both have 2 maps, while your 2nd map is hidden in recursion.

**Comment by divyanshu-rawat** [comment]
Yup I did the performance analysis on develop by copying your code & mine here are the reports.

My

Screenshot 2020-04-03 at 15 28 20


Yours

Screenshot 2020-04-03 at 15 30 46

**Comment by divyanshu-rawat** [comment]
> Interesting,
> 
> Lets now assume 1 edge having 10 children each children has 10 children.
> 
> ## My approach
> ```js
> edges.map
> ```
> 
> 1 iteration.
> 
> ```js
> edges.children.map
> ```
> 
> 10 iterations.
> 
> in each iteration `NavigationLayers` is called.
> 
> ```js
> edges.children.map
> ```
> 
> 10 iterations.
> 
> _**Total iterations**_ : 100
> 
> ## Your approach
> ```
> edge.map
> ```
> 
> 1 iteration
> 
> `Layers` will be called.
> `Extension` will be called.
> Edge has 10 children, again `NavigationLayers` will be called.
> 
> ```js
> edges.map
> ```
> 
> 10 Iterations.
> 
> In each iteration `Layers` will be called.
> `Extension` will be called.
> Each edge has 10 children, again `NavigationLayers` will be called.
> 
> ```js
> edges.map
> ```
> 
> 10 Iterations.
> 
> As no edge has children, no further `NavigationLayers` call.
> 
> _**Total Iterations:**_ 100
> 
> #### We both have 2 maps call, while your 2nd map call is hidden in recursion.

Quoting.

> We both have 2 maps call, while your 2nd map call is hidden in recursion.

And I think hidden one in recursion saves time, in similar manner all other calls hidden in recursion does.

**Comment by Marvin9** [comment]
Performance analysis was good option. Whatever, This discussion was just to clear few doubts. Your approach is readable and performance is great too. 

Closing this one.

**Comment by divyanshu-rawat** [comment]
@Marvin9 that's nice if you! can you please add margin support to mine one if you have time.

**Pull request closed without merging**
