### PR TITLE
Added opportunities filter ☘️

### LINKED ISSUE #609: Dashboard: Opportunities Filters
**Describe the solution you'd like**
Implementation of the attached Opportunity based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Templates](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Templates) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/uikit` route. 
But you would need to divide this component into different atoms and molecules:
- **Tags** ,**dropdown**, **Dropdown buttons** and **reset filter button** will come under `Atoms`
- **Search** input will come under `Molecules`
- Card CSS should be the same as mentioned in Atoms. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download SVG icons from the figma and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

Capture

For each dropdown refer to the images below.

Internship Date-dropdown

Internship Job-dropdown

Internship Location-dropdown

### PR DESCRIPTION
**Pull request by BhuwanChandra**
Fixes #609 

Capture

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@BhuwanChandra I will merge it in a day or two, you can pick up another issue if you want, else let me know if you need another issue :)

**Comment by BhuwanChandra** [comment]
@divyanshu-rawat do I need to remove Hound warnings?

**Comment by divyanshu-rawat** [comment]
I will cleanup a bit thanks :) , feel free to pick up another issue :)

**Comment by BhuwanChandra** [comment]
@divyanshu-rawat please also add the difficulty labels of the related issue.

**Comment by divyanshu-rawat** [comment]
@BhuwanChandra difficulty levels are already there.

**Comment by BhuwanChandra** [comment]
@divyanshu-rawat Oh, sorry, I was saying that link the related issue with PR so that it gets evaluated.

**Pull request merged**
