### PR TITLE
added unit test for Overlay component

### PR DESCRIPTION
**Pull request by Dishebh**
For issue: #519

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@Marvin9 if you have time please have a look :)

**Comment by divyanshu-rawat** [comment]
@Marvin9 if you get time feel free to have a look :)

**Comment by divyanshu-rawat** [comment]
@Marvin9 scope out?

**Comment by Marvin9** [comment]
Related to #871 . @Dishebh will resolve it.

**Comment by Dishebh** [comment]
Updated the test :+1: @Marvin9 @divyanshu-rawat

**Pull request merged**
