### PR TITLE
Master > Develop

### PR DESCRIPTION
**Pull request by divyanshu-rawat**
1. Progress towards TypeScript. #741  🎓
2. Removed unwanted space of sidebar. #748. 🔨
3. Input with Icon UI #728 🚀
4. Bugfix/signup page #745 🙌🏻
5. Multimedia Text Input UI #742 🎸
6. Added publications input #749 🚀
7. Hooray Overlay UI added #713 ☘️

### CODE REVIEW

**Comment by Marvin9** [comment]
Looking good. 👍

Any thoughts on passing ```value``` and ```onChange``` as props in defaultIconInput? Otherwise how can we utilize input value?

**Comment by divyanshu-rawat** [comment]
> Looking good. 👍
> 
> Any thoughts on passing `value` and `onChange` as props in defaultIconInput? Otherwise how can we utilize input value?

it already has handleChange as prop isn't it? 😕

**Comment by divyanshu-rawat** [comment]
oh okay you mean handleChange yes we can do it-

**Comment by divyanshu-rawat** [comment]
@Marvin9 I have adde `handleChange` in this PR https://github.com/Ignitus/Ignitus-client/pull/749

**Comment by divyanshu-rawat** [comment]
@Marvin9 merging this to `master` as of now but not releasing anything 🙌🏻

**Pull request merged**
