### PR TITLE
Pure footer ★☘️🚀🎯

### PR DESCRIPTION
**Pull request by abhu-A-J**
addresses #403 

@divyanshu-rawat I think I managed to do the tasks. Somehow the footer was more complicated than the navbar 😆. 

Let me know if any changes are needed. 

Here's the working :

Ignitus (1)

### CODE REVIEW

**Comment by abhu-A-J** [comment]
> LGTM, Will refactor a bit & then merge it 🥇

Cool! Thanks

**Comment by divyanshu-rawat** [comment]
@abhu-A-J if you are interested to see typescript conversion have a look to my this commit. https://github.com/Ignitus/Ignitus-client/pull/699/commits/52bc93d30eb1492147279bdf7749929f73180995

**Comment by abhu-A-J** [comment]
> @abhu-A-J if you are interested to see typescript conversion have a look to my this commit. [52bc93d](https://github.com/Ignitus/Ignitus-client/commit/52bc93d30eb1492147279bdf7749929f73180995)

Sure will definitely check it out.

**Comment by divyanshu-rawat** [comment]
@abhu-A-J please check this commit as well https://github.com/Ignitus/Ignitus-client/pull/699/commits/c58999fdc79a080e21e0b157fb1153204239878c.

**Pull request merged**
